# Generated by Django 5.1.3 on 2024-11-28 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category')},
        ),
        migrations.AddField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transportation', 'Transportation'), ('utilities', 'Utilities'), ('housing', 'Housing'), ('healthcare', 'Healthcare'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('education', 'Education'), ('personal_care', 'Personal Care'), ('debt_payments', 'Debt Payments'), ('savings', 'Savings & Investments'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transportation', 'Transportation'), ('utilities', 'Utilities'), ('housing', 'Housing'), ('healthcare', 'Healthcare'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('education', 'Education'), ('personal_care', 'Personal Care'), ('debt_payments', 'Debt Payments'), ('savings', 'Savings & Investments'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('business', 'Business'), ('freelancing', 'Freelancing'), ('investments', 'Investments'), ('rental', 'Rental'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
    ]
