# Generated by Django 5.1.3 on 2024-11-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_expense_user_remove_income_user_delete_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('BDT', 'Bangladeshi Taka'), ('INR', 'Indian Rupee'), ('JPY', 'Japanese Yen')], default='BDT', max_length=3),
        ),
    ]
