# Generated by Django 5.1.3 on 2024-11-28 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('BUSINESS', 'Business'), ('FREELANCE', 'Freelance'), ('INVESTMENT', 'Investment'), ('OTHER_INCOME', 'Other Income'), ('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('UTILITIES', 'Utilities'), ('RENT', 'Rent'), ('SHOPPING', 'Shopping'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('OTHER_EXPENSE', 'Other Expense')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SALARY', 'Salary'), ('BUSINESS', 'Business'), ('FREELANCE', 'Freelance'), ('INVESTMENT', 'Investment'), ('OTHER_INCOME', 'Other Income'), ('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('UTILITIES', 'Utilities'), ('RENT', 'Rent'), ('SHOPPING', 'Shopping'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('OTHER_EXPENSE', 'Other Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category', 'month')},
            },
        ),
    ]
